name: Test Workflow

on: 
  push:
  workflow_dispatch:  # Permite ejecución manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: echo "GitHub Actions is working!"
